### ISSUE TITLE
Fatal error during initialization when unknown device encountered

### ISSUE THREAD

**Issue by wojo** [dkerr64/homebridge-yolink#51]
**Describe The Bug:**
One of my devices is failing on enumeration with the following error. I believe this is making the enumeration stop at 22 out of 29 devices, which I think is the Power Failure Alarm, and this also may causing any updates to fail (opening a door does not reflect in HomeKit).

**To Reproduce:**
Just load up devices, which includes a Power Failure Alarm it seems.

**Expected behavior:**
No error, however since the power failure alarm has a battery this is quite odd. I couldn't locate the API specs for this sensor.

**Logs:**

```
[9/11/2022, 8:05:29 PM] [YoLink] [verbose] Restoring accessory from cache: Power Failure Alarm (d88b4c010003d8b4)
[9/11/2022, 8:05:29 PM] [YoLink] Fatal error during YoLink plugin initialization:
TypeError: Cannot read properties of undefined (reading 'hasBattery')
    at YoLinkPlatformAccessory.initializeDeviceVars (/homebridge/node_modules/homebridge-yolink/src/platformAccessory.ts:105:53)
    at new YoLinkPlatformAccessory (/homebridge/node_modules/homebridge-yolink/src/platformAccessory.ts:46:10)
    at YoLinkHomebridgePlatform.registerDevices (/homebridge/node_modules/homebridge-yolink/src/platform.ts:199:28)
    at YoLinkHomebridgePlatform.discoverDevices (/homebridge/node_modules/homebridge-yolink/src/platform.ts:140:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Plugin Config:**

```json
        {
            "name": "YoLink",
            "platform": "YoLink",
            "tokenURL": "https://api.yosmart.com/open/yolink/token",
            "apiURL": "https://api.yosmart.com/open/yolink/v2/api",
            "mqttPort": 8003,
            "userAccessId": "xxx",
            "secretKey": "xxx",
            "refreshAfter": 14500,
            "verboseLog": true,
            "liteLog": true,
            "allDevices": true,
            "deviceTemperatures": true,
            "enableExperimental": true,
            "_bridge": {
                "username": "xxx",
                "port": 54871
            }
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.7
* **Homebridge Version**: 1.5.0
* **Node.js Version**: v16.16.0
* **NPM Version**: 8.11.0
* **Operating System**: Docker

**Comment by wojo** [comment]
Adding a device override for the Power Failure Alarm restores functionality and allows events to flow:

```
                {
                    "deviceId": "xxx",
                    "config": {
                        "hide": "true"
                    }
                }
```

**Comment by dkerr64** [comment]
Well, that is bad... in that one device (in this case "unsupported") should cause fatal error.  I will look at it this evening and get a fix out asap.

This device must be returning data different from other devices.  Could you turn on verbose logging and capture the data returned please.  Early in the startup phase there should be a (fairly long in your case) JSON data record (data bounded by curly braces) listing all your devices.  Search for "Home.getDeviceList" in the log.  I would like to see that.

Then later in the log, probably just before the crash, there may be another JSON data string specific to the failing device.  It will have "xxxx.getState" in the data.  I don't know what xxxx will be for this device.

**Comment by dkerr64** [comment]
> 

Did you just recently update the plugin? Another possible fix may be to remove this device from the cache then restart.  Go to Homebridge settings (upper right three dots) and "remove single cached accessory" look for this one and remove it.  **Do not** select option to remove all accessories, that is likely to cause you a lot of work as removing an accessory will then remove any automations you had set for it in HomeKit (which won't be restored when the accessory is added back in).

**Comment by wojo** [comment]
@dkerr64 sent via email as it does include exact device IDs, UDIDs, etc.

Yesterday was my first time installing the plugin and it never made it into the device cache.

**Comment by dkerr64** [comment]
Thanks for the logs.  I see where the bug is and will fix it this evening.

The fix will stop the fatal error.  But the device will be "unknown" to the plugin, so not visible in HomeKit.  I will open a new issue to log the request to support PowerFailureAlarm device types.

Thanks

**Comment by dkerr64** [comment]
Fixed in 1.2.8

**Comment by wojo** [comment]
Confirmed working!

**Comment by dkerr64** [comment]
Thank you.  Over to issue #53 to discuss adding support for the device now that the immediate bug is fixed.
