### ISSUE TITLE
Garage controller accessory shows up as generic switch

### ISSUE THREAD

**Issue by crazyfoxkp** [dkerr64/homebridge-yolink#61]
Hi- 
Thanks for your efforts. 
Using yolink plugin v 1.3, setup as child bridge on Docker/Synology. 
Under Accessories (Homebridge UI) tab - do not see garage controller accessory. Garage controller, sensor, and battery level displayed separately for ungrouped devices. For 1 grouped set (garage controller and sensor) only see a switch listing. 
Also, same findings on HomeKit. Controllers are displayed/behaving as simple switches.
I think the expected behavior is to show open-closed-state, opening-closing transition state, and display as garage door. 
Tried removing and reinstalling child-bridge accessory / resetting the hub on HomeKit. 

Any ideas?

**Comment by dkerr64** [comment]
Have you setup the garage door sensor and controller in the config file (or with the config UI)?  You should have something that looks like this..

```
"garageDoors": [
                {
                    "controller": "0123456789abcdef",
                    "sensor": "abcdef0123456789",
                    "timeout": 45
                }
            ] 
```
If you have not assigned a controller and sensor to a garage door as above then yes, each device will show separately.

If you have that, then l need to see whether there are any errors or warnings in the log file.

Thanks

**Comment by crazyfoxkp** [comment]
I have one controller/sensor set grouped and another without. The grouped item displays as one unit (without sensor) but acts/displays as a switch, and doesn't provide state info. 

Log file attached. 

[homebridge.log.txt](https://github.com/dkerr64/homebridge-yolink/files/9726856/homebridge.log.txt)
Thanks for helping.

**Comment by dkerr64** [comment]
The clue is in this log file message...
```
[10/5/2022, 11:37:08 AM] [YoLink] Garage Door must have two known devices. Ignoring this door:
{"controller":"d8864c010003f92e","sensor":"d88b4c020006740a"}
```
You mistyped the UID for the controller... value in position 4 is wrong.  This line should have appeared in the homebridge log viewer highlighted in orange to draw your attention.

**Comment by crazyfoxkp** [comment]
Hi-
Reentered UID and all work as expected. Issue resolved.
Thanks again for doing this project and helping me troubleshoot. 
Cheers
