### ISSUE TITLE
Pull temperature in Farenheit

### ISSUE THREAD

**Issue by mehh** [dkerr64/homebridge-yolink#68]
**Is your feature request related to a problem? Please describe:**
Temperatures are currently reported only in Celsius.  Would be nice to have the option to use either Celsius or Fahrenheit.

**Describe the solution you'd like:**
An optional parameter that would let you retrieve and pass the temperature in the desired format.

**Describe alternatives you've considered:**
None

**Additional context:**
None

**Comment by dkerr64** [comment]
This is not a function of a plugin.  You can select to display in Celsius of Fahrenheit in the homebridge settings and/or in the Apple iPhone or iPad or Mac region settings.  The API always reports in Celsius.
