### ISSUE TITLE
Support for Relay 

### ISSUE THREAD

**Issue by btgh** [dkerr64/homebridge-yolink#77]
**Is your feature request related to a problem? Please describe:**

Support for the Yolink Relay device
**Describe the solution you'd like:**

I would like the ability to remotely control my pool pump via contact closure switches 
**Describe alternatives you've considered:**

**Additional context:**

**Comment by btgh** [comment]
Great plugin!   I’ve been looking for homekit support for yolink for some time.

**Comment by dkerr64** [comment]
I need to see the logs... if the relay is not recognized then it will be reported in the log with a statement that the device is unsupported.  And then accompanying useful information in JSON format.  You should see this during initialization and maybe also whenever the device reports status (so, e.g. if you manually turn the really on/off then that may cause a message to log that the plugin received something it does not know about).

Thanks
David

**Comment by btgh** [comment]
My mistake - it shows up as a switch.  I didn’t see it in the documentation so I assume it was not supported.

**Comment by dkerr64** [comment]
Thanks for testing.  Next time I am in the readme, I'll add it to the list.
