### ISSUE TITLE
Is Water Leak Sensor 2 supported?

### ISSUE THREAD

**Issue by LordZork** [dkerr64/homebridge-yolink#78]
Hello,

Based on the ReadMe, I can see that this plugin supports the original YoLink leak sensor (below)...

[Water Leak Sensor 1](https://shop.yosmart.com/products/ys7903) (YS7903-UC)

However, I am wondering if this plugin also supports the other leak sensors (below)?...

[Water Leak Sensor 2](https://shop.yosmart.com/products/ys7904g) (YS5704-UC)

[Water Leak Sensor 3](https://shop.yosmart.com/products/ys7904w-2) (YS7904-UC)

[Water Level Monitoring Sensor](https://shop.yosmart.com/products/ys7904w) (YS7904-UC)

[Water Level Monitoring Sensor w/Float Switch](https://shop.yosmart.com/products/ys7904f) (YS7904F-UC)

It is my understanding that the last four leak sensors (above) all use the same [Water Leak Sensor 2](https://shop.yosmart.com/products/ys7904g) device, with the only difference being the included attachment – i.e., a [sensor cable](https://shop.yosmart.com/products/sensor-cable-1m), a [sensor probe](https://shop.yosmart.com/products/water-sensor-probe), or a [sensor float switch](https://shop.yosmart.com/products/pfs).

As such, I am specifically wondering if this plugin supports [Water Leak Sensor 2](https://shop.yosmart.com/products/ys7904g) as well as [Water Leak Sensor 1](https://shop.yosmart.com/products/ys7903)?

**Comment by dkerr64** [comment]
@LordZork I do not have any of these new leak sensors to test with, however I suspect that they will work.  The [YoLink API](http://doc.yosmart.com/docs/overall/intro) does not publish anything specific for the original or newer leak sensors, so they are likely to work the same.

If you try one then please let me know.  If it does not work then I can work with you to figure out what is different... this plugin is designed to log when an unsupported device is connected or an unsupported message received, and the log detail informs me what to do to add support.

Thanks
David

**Comment by dkerr64** [comment]
Closing as no follow-up discussion.
