### ISSUE TITLE
EVO water valve error since update 1.4.1

### ISSUE THREAD

**Issue by threeonparfive** [dkerr64/homebridge-yolink#87]
**Describe The Bug:**
Following the latest plugin upgrade, that status of the valve may no longer be accurately reflected in Homebridge and Homekit.  I had an even that shut the valve off yet the status in Homekit still showed it to be on.  I then noticed the attached error message int he logs.

**To Reproduce:**

**Expected behavior:**

**Logs:**

[11/23/2023, 3:38:00 PM] [YoLink] MQTT: Manipulator.StatusChange for device Main Water Valve (d88b4c0100081e51) not supported.
Please report all bugs at https://github.com/dkerr64/homebridge-yolink/issues
{"event":"Manipulator.StatusChange","time":1700771880160,"msgid":"1700771880159","data":{"state":"closed","loraInfo":{"netId":"010201","signal":-56,"gatewayId":"d88b4c160303664a","gateways":1}},"deviceId":"d88b4c0100081e51"}
[11/23/2023, 3:38:01 PM] [YoLink] MQTT: Manipulator.StatusChange for device Main Water Valve (d88b4c0100081e51) not supported.
Please report all bugs at https://github.com/dkerr64/homebridge-yolink/issues
{"event":"Manipulator.StatusChange","time":1700771881362,"msgid":"1700771881362","data":{"state":"closed","loraInfo":{"netId":"010201","signal":-57,"gatewayId":"d88b4c160303664a","gateways":1}},"deviceId":"d88b4c0100081e51"}

**Plugin Config:**

```json
{
    "name": "YoLink",
    "platform": "YoLink",
    "tokenURL": "https://api.yosmart.com/open/yolink/token",
    "apiURL": "https://api.yosmart.com/open/yolink/v2/api",
    "mqttPort": 8003,
    "userAccessId": "xxxxxxx",
    "secretKey": "xxxxxxx",
    "refreshAfter": 14500,
    "verboseLog": false,
    "liteLog": true,
    "allDevices": true,
    "excludeTypes": [
        "Hub",
        "SpeakerHub"
    ],
    "deviceTemperatures": false,
    "enableExperimental": false,
    "_bridge": {
        "username": "xxxxx",
        "port": 30870
    }
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.4.1
* **Homebridge Version**: 1.7.0
* **Node.js Version**: 18.15.0
* **NPM Version**: 
* **Operating System**:  Synology

**Comment by dkerr64** [comment]
So, that's a new product from YoLink.  The problem existed before v1.4.1 though some of the changes I implemented in that release may have made it more visible.

The MQTT message you show in the log is new, I had not seen it before, so I was not supporting it.  But that is the purpose of logging it, so that when new messages show up there is enough information to add the support when someone opens an issue.  THANK YOU for reporting this.

Please try v1.4.2 that I just published, I have added support for this message and I believe it should work for you.

**Comment by threeonparfive** [comment]
Working as expected now.  Thanks for the rapid response!
