### ISSUE TITLE
Support for YoLink Mini Plug

### ISSUE THREAD

**Issue by jeperry** [dkerr64/homebridge-yolink#91]
Just hoping for basic Homekit support for YoLink's inexpensive smart plugs. Thank you!

**Comment by dkerr64** [comment]
Specifically what device are you looking at?  I have YoLink smart plugs working fine with this plugin.

**Comment by jeperry** [comment]
I recently added the '[YoLink Mini Plug](https://www.amazon.com/dp/B085LC46RF?psc=1&ref=ppx_yo2ov_dt_b_product_details)' to my YoLink Hub. It works fine in YoLink's App. I've been using the Homebridge plugin with the Temperature/Humidity Sensor for a while now with no issues seeing it in Homekit (via the iOS Home App), so I thought when I added the plug it would also show up there, but I do not see it. Apologies if I have missed something.

**Comment by dkerr64** [comment]
Can you tell me the model number please… you can find that in the YoLink app.  E.g. mine are YS6604-UC

Thanks

**Comment by jeperry** [comment]
Mine is the very same - YS6604-UC. 
I had already restarted Homebridge and the plugin is up to date. Seems like I should try disabling and enabling the plugin. Thank you again for the help.

**Comment by jeperry** [comment]
Plugin restart seemed to work. Sorry for the noise and thank you for providing this plugin.

**Comment by dkerr64** [comment]
@jeperry Thank you for letting me know.  I thought I had implemented a way to detect new devices added without requiring a plugin restart, I will have to look at that and check if there is a bug somewhere.
