### ISSUE TITLE
Accessories showing in HomeKit but not responding 

### ISSUE THREAD

**Issue by CharlesGroleau44** [dkerr64/homebridge-yolink#97]
I reinstalled the plugin.
All accessories seems to have load.
They also show on Hoobs accessories dashboard but not responding. 
I also reinstalled the hub in Apple Home Kit. 
All accessories loaded. 
Showing but not updating status.
I get this message in Hoobs logs.
ERROR[31mThe plugin "homebridge-yolink" requires a Homebridge version of ^1.6.0 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m

**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by dkerr64** [comment]
HOOBS is a commercial product and I do not own one so this plugin has never been tested with it.  Based on the log message you provided, it appears that it is using an older version of Homebridge.

I suggest you ask them about whether they support this plugin on their product.

Thanks.

**Comment by CharlesGroleau44** [comment]
Many thanks for your return and sorry for bothering you.
Have a nice week.
￼

**Comment by dkerr64** [comment]
Closing as no follow-up discussion.
